---
- name: Configure Jenkins Master - Docker Install
  hosts: all
  gather_facts: false

  tasks:
    - name: Load variables for install-docker playbook
      ansible.builtin.include_vars:
        file: jenkins-vars.yml
      tags:
        - load-variables

    - name: Disable Selinux
      ansible.posix.selinux:
        state: disabled
      tags:
        - disable_selinux

    - name: Dnf upgrade (yum upgrade)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      tags:
        - dnf_upgrade

    - name: Add jenkins to repo
      ansible.builtin.get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/
        mode: 644
      tags:
        - add-jenkins-repo

    - name: Import jenkins repo key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      tags:
        - import-jenkins-key

    - name: Install java
      ansible.builtin.dnf:
        name: '{{ packages }}'
        state: latest
      tags:
        - install-java

    - name: Install jenkins
      ansible.builtin.dnf:
        name: jenkins
        state: latest
      notify:
        - Start jenkins
      tags:
        - install-jenkins

    - name: Add jenkins to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/jenkins
        line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: '440'
        create: true
        validate: 'visudo -cf %s'
      tags:
        - add-jenkins-sudoers

    - name: Add jenkins to docker group
      ansible.builtin.user:
        name: jenkins
        comment: jenkins server
        groups: docker
      tags:
        - add-jenkins-to-docker-grp

  handlers:
    - name: Start jenkins
      ansible.builtin.systemd_service:
        name: jenkins
        state: restarted
        enabled: true
...
