---
- name: Jenkins Master Docker Config
  hosts: all

  tasks:
    - name: Load variables for install-docker.yml playbook
      ansible.builtin.include_vars:
        file: docker-vars.yml
      tags:
        - load_docker_variables

    - name: Dnf update
      ansible.builtin.dnf:
        name: '*'
        state: latest
      tags:
        - dnf_update

    - name: Install Docker dependencies
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest
      tags:
        - install_docker_dependencies

    - name: Add docker repo to CentOS
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/
        mode: '644'
      tags:
        - add_docker_repo

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        state: latest
      notify:
        - Start docker
      tags:
        - install_docker

  handlers:
    - name: Start docker
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true
...
